# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doctor_portal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QLabel
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtCore import Qt


class DoctorPortal(QMainWindow):
    def __init__(self, doctor_list, parent=None):
        super(DoctorPortal, self).__init__(parent)
        self.doctor_list = doctor_list
        self.counter = -1
        self.setup_ui(self)

        self.next_button.clicked.connect(self.next_button_clicked)
        self.previous_button.clicked.connect(self.previous_button_clicked)


    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("centralwidget")
        self.picture_label = QtWidgets.QLabel(self.central_widget)
        self.picture_label.setGeometry(QtCore.QRect(20, 80, 241, 211))
        self.picture_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.picture_label.setAlignment(QtCore.Qt.AlignCenter)
        self.picture_label.setObjectName("picture_label")
        self.form_layout_widget = QtWidgets.QWidget(self.central_widget)
        self.form_layout_widget.setGeometry(QtCore.QRect(330, 130, 250, 91))
        self.form_layout_widget.setObjectName("formLayoutWidget")
        self.doctor_form_layout = QtWidgets.QFormLayout(self.form_layout_widget)
        self.doctor_form_layout.setContentsMargins(0, 0, 0, 0)
        self.doctor_form_layout.setObjectName("doctor_form_layout")
        self.first_name_label = QtWidgets.QLabel(self.form_layout_widget)
        self.first_name_label.setObjectName("first_name_label")
        self.doctor_form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.first_name_label)
        self.first_name_field = QtWidgets.QLineEdit(self.form_layout_widget)
        self.first_name_field.setObjectName("first_name_field")
        self.doctor_form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.first_name_field)
        self.last_name_label = QtWidgets.QLabel(self.form_layout_widget)
        self.last_name_label.setObjectName("last_name_label")
        self.doctor_form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.last_name_label)
        self.specialty_label = QtWidgets.QLabel(self.form_layout_widget)
        self.specialty_label.setObjectName("specialty_label")
        self.doctor_form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.specialty_label)
        self.last_name_field = QtWidgets.QLineEdit(self.form_layout_widget)
        self.last_name_field.setObjectName("last_name_field")
        self.doctor_form_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.last_name_field)
        self.specialty_field = QtWidgets.QLineEdit(self.form_layout_widget)
        self.specialty_field.setObjectName("specialty_field")
        self.doctor_form_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.specialty_field)
        self.next_button = QtWidgets.QPushButton(self.central_widget)
        self.next_button.setGeometry(QtCore.QRect(465, 250, 75, 23))
        self.next_button.setObjectName("next_button")
        self.previous_button = QtWidgets.QPushButton(self.central_widget)
        self.previous_button.setGeometry(QtCore.QRect(355, 250, 75, 23))
        self.previous_button.setObjectName("previous_button")
        self.previous_button.setEnabled(False)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslate_ui(MainWindow)
        self.load_image("default_picture.png")
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.picture_label.setText(_translate("MainWindow", "Doctor\'s Photo Goes Here"))
        self.first_name_label.setText(_translate("MainWindow", "First Name"))
        self.last_name_label.setText(_translate("MainWindow", "Last Name"))
        self.specialty_label.setText(_translate("MainWindow", "Speciality"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.previous_button.setText(_translate("MainWindow", "Previous"))

    def load_image(self, img):
        my_image = QImage()
        my_image.loadFromData(self.read_image(img))  # loadFromData also accepts images as a byte-array/string of bytes
        w = 250  # set a value for your scaled width here
        h = 250  # set a value for your scaled height here

        pixmap = QPixmap.fromImage(my_image)
        scaled_img = pixmap.scaled(w, h, Qt.KeepAspectRatio)
        self.picture_label.setPixmap(scaled_img)

    def read_image(self, img_file):
        img_bytes = open(img_file, "rb").read()
        return img_bytes

    def next_button_clicked(self):
        if self.counter == -1:
            self.previous_button.setEnabled(True)
        elif self.counter == len(self.doctor_list) - 2:
            self.next_button.setEnable(False)

        if self.counter < len(self.doctor_list) - 1:
            self.counter += 1
            doctor = self.doctor_list[self.counter]
            self.first_name_field.setText(doctor.get_first_name())
            self.last_name_field.setText(doctor.get_last_name())
            self.specialty_field.setText(doctor.get_specialty())
            if doctor.get_gender() == 'M':
                self.load_image("male_picture.png")
            elif doctor.get_gender() == 'F':
                self.load_image("female_picture.png")
            else:
                self.load_image("default_picture.png")

    def previous_button_clicked(self):
        if self.counter == len(self.doctor_list) - 1:
            self.next_button.setEnable(True)

        if self.counter == 0:
            self.previous_button.setEnabled(False)
            self.counter -= 1
            self.first_name_field.setText('')
            self.last_name_field.setText('')
            self.specialty_field.setText('')
            self.load_image("default_picture.png")

        elif self.counter > 0:
            self.counter -= 1
            doctor = self.doctor_list[self.counter]
            self.first_name_field.setText(doctor.get_first_name())
            self.last_name_field.setText(doctor.get_last_name())
            self.specialty_field.setText(doctor.get_specialty())
            if doctor.get_gender() == 'M':
                self.load_image("male_picture.png")
            elif doctor.get_gender() == 'F':
                self.load_image("female_picture.png")
            else:
                self.load_image("default_picture.png")